config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :game_picks
  resources :leagues
  resources :standings, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'picks', to: 'game_picks#index', as: 'picks'
  get 'about', to: 'about#about', as: 'about'
end

app/models/standing.rb
class Standing < ApplicationRecord
end

app/controllers/standings_controller.rb
class StandingsController < ApplicationController
  before_action :set_standing, only: [:show, :edit, :update, :destroy]

  # GET /standings
  # GET /standings.json
  def index
    @standings = Standing.all
  end

  # GET /standings/1
  # GET /standings/1.json
  def show
  end

  # GET /standings/new
  def new
    @standing = Standing.new
  end

  # GET /standings/1/edit
  def edit
  end

  # POST /standings
  # POST /standings.json
  def create
    @standing = Standing.new(standing_params)

    respond_to do |format|
      if @standing.save
        format.html { redirect_to @standing, notice: 'Standing was successfully created.' }
        format.json { render :show, status: :created, location: @standing }
      else
        format.html { render :new }
        format.json { render json: @standing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /standings/1
  # PATCH/PUT /standings/1.json
  def update
    respond_to do |format|
      if @standing.update(standing_params)
        format.html { redirect_to @standing, notice: 'Standing was successfully updated.' }
        format.json { render :show, status: :ok, location: @standing }
      else
        format.html { render :edit }
        format.json { render json: @standing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /standings/1
  # DELETE /standings/1.json
  def destroy
    @standing.destroy
    respond_to do |format|
      format.html { redirect_to standings_url, notice: 'Standing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_standing
      @standing = Standing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def standing_params
      params.require(:standing).permit(:place, :score)
    end
end

app/helpers/standings_helper.rb
module StandingsHelper
end

app/views/standings/_form.html.erb
<%= form_with(model: standing, local: true) do |form| %>
  <% if standing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(standing.errors.count, "error") %> prohibited this standing from being saved:</h2>

      <ul>
      <% standing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/standings/edit.html.erb
<h1>Editing Standing</h1>

<%= render 'form', standing: @standing %>

<%= link_to 'Show', @standing %> |
<%= link_to 'Back', standings_path %>

app/views/standings/index.html.erb
<%= render 'layouts/navigationSignedIn' %>
<p id="notice"><%= notice %></p>

<h1>Standings</h1>

<table>
  <thead>
    <tr>
      <th>Place</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @standings.each do |standing| %>
      <tr>
        <td><%= standing.place %></td>
        <td><%= standing.score %></td>
        <td><%= link_to 'Show', standing %></td>
        <td><%= link_to 'Edit', edit_standing_path(standing) %></td>
        <td><%= link_to 'Destroy', standing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/standings/new.html.erb
<h1>New Standing</h1>

<%= render 'form', standing: @standing %>

<%= link_to 'Back', standings_path %>

app/views/standings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Place:</strong>
  <%= @standing.place %>
</p>

<p>
  <strong>Score:</strong>
  <%= @standing.score %>
</p>

<%= link_to 'Edit', edit_standing_path(@standing) %> |
<%= link_to 'Back', standings_path %>