config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :game_picks
  resources :leagues
  resources :standings, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'picks', to: 'game_picks#index', as: 'picks'
  get 'about', to: 'about#about', as: 'about'
end

app/models/game_pick.rb
class GamePick < ApplicationRecord
  belongs_to :user
  
  validates :team1, :team2, :week, :pickedteam, :spread, :gamedatetime, presence: true
end

app/controllers/game_picks_controller.rb
class GamePicksController < ApplicationController
  before_action :set_game_pick, only: [:show, :edit, :update, :destroy]

  # GET /game_picks
  # GET /game_picks.json
  def index
    if current_user
    else
      redirect_to "/login"
    end
    week = params[:week]
    if week == nil
      week = "1"
    end
    game_info_object = GameInfo.new(week)
    @game_infos = game_info_object.get_game_info()      
    @game_picks = GamePick.all
    
    @game_infos.each do |game_info|
      correct_game = @game_picks.select{ |game_pick| game_pick.team1 == game_info["schedule"]["homeTeam"]["abbreviation"] && game_pick.team2 == game_info["schedule"]["awayTeam"]["abbreviation"] && game_pick.week == game_info["schedule"]["week"] && game_pick.user_id == session[:user_id]}
      if correct_game[0] != nil
        game = correct_game[0]
        game_info["schedule"]["pickedTeam"] = game.pickedteam
        game_info["schedule"]["spread"] = game.spread
      else
        game_info["schedule"]["pickedTeam"] = ""
        game_info["schedule"]["spread"] = 0
      end
      
    end
    
    respond_to do |format|
      format.html {render :index}
      format.json {render :index, status: :ok}
      format.xml {render xml: @game_picks.as_json}
    end 
  end

  # GET /game_picks/1
  # GET /game_picks/1.json
  def show
  end

  # GET /game_picks/new
  def new
    @game_pick = GamePick.new
  end

  # GET /game_picks/1/edit
  def edit
  end

  # POST /game_picks
  # POST /game_picks.json
  def create
    @game_pick = GamePick.find_or_initialize_by(team1: game_pick_params[:team1], team2: game_pick_params[:team2], week: game_pick_params[:week])
    @game_pick[:pickedteam] = game_pick_params[:pickedteam]
    @game_pick[:spread] = game_pick_params[:spread]
    @game_pick[:gamedatetime] = game_pick_params[:gamedatetime]
    
    @game_pick.build_user(:id => session[:user_id])

    respond_to do |format|
      puts @game_pick.inspect
      if @game_pick.save
        format.html { redirect_to @game_pick, notice: 'Game pick was successfully created.' }
        format.json { render :show, status: :created, location: @game_pick }
      else
        format.html { render :new }
        format.json { render json: @game_pick.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_picks/1
  # PATCH/PUT /game_picks/1.json
  def update
    respond_to do |format|
      if @game_pick.update(game_pick_params)
        format.html { redirect_to @game_pick, notice: 'Game pick was successfully updated.' }
        format.json { render :show, status: :ok, location: @game_pick }
      else
        format.html { render :edit }
        format.json { render json: @game_pick.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_picks/1
  # DELETE /game_picks/1.json
  def destroy
    @game_pick.destroy
    respond_to do |format|
      format.html { redirect_to game_picks_url, notice: 'Game pick was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_pick
      @game_pick = GamePick.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_pick_params
      params.require(:game_pick).permit(:team1, :team2, :week, :pickedteam, :spread, :gamedatetime, :user_id)
    end
end

app/helpers/game_picks_helper.rb
module GamePicksHelper
end

app/views/game_picks/_form.html.erb
<%= form_with(model: game_pick, local: true) do |form| %>
  <% if game_pick.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game_pick.errors.count, "error") %> prohibited this game_pick from being saved:</h2>

      <ul>
      <% game_pick.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :team1 %>
    <%= form.text_field :team1 %>
  </div>

  <div class="field">
    <%= form.label :team2 %>
    <%= form.text_field :team2 %>
  </div>

  <div class="field">
    <%= form.label :week %>
    <%= form.number_field :week %>
  </div>

  <div class="field">
    <%= form.label :pickedteam %>
    <%= form.text_field :pickedteam %>
  </div>

  <div class="field">
    <%= form.label :spread %>
    <%= form.number_field :spread %>
  </div>

  <div class="field">
    <%= form.label :gamedatetime %>
    <%= form.datetime_local_field :gamedatetime %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/game_picks/edit.html.erb
<h1>Editing Game Pick</h1>

<%= render 'form', game_pick: @game_pick %>

<%= link_to 'Show', @game_pick %> |
<%= link_to 'Back', game_picks_path %>

app/views/game_picks/index.html.erb
<%= render 'layouts/navigationSignedIn' %>
<p id="notice"><%= notice %></p>

<div id="weeksNav">
  <p>
    Weeks: 
    <%= link_to "1", {:controller => "game_picks", :method => "index", :week => "1" }%>|
    <%= link_to "2", {:controller => "game_picks", :method => "index", :week => "2" }%>|
    <%= link_to "3", {:controller => "game_picks", :method => "index", :week => "3" }%>|
    <%= link_to "4", {:controller => "game_picks", :method => "index", :week => "4" }%>|
    <%= link_to "5", {:controller => "game_picks", :method => "index", :week => "5" }%>|
    <%= link_to "6", {:controller => "game_picks", :method => "index", :week => "6" }%>|
    <%= link_to "7", {:controller => "game_picks", :method => "index", :week => "7" }%>|
    <%= link_to "8", {:controller => "game_picks", :method => "index", :week => "8" }%>|
    <%= link_to "9", {:controller => "game_picks", :method => "index", :week => "9" }%>|
    <%= link_to "10", {:controller => "game_picks", :method => "index", :week => "10" }%>|
    <%= link_to "11", {:controller => "game_picks", :method => "index", :week => "11" }%>|
    <%= link_to "12", {:controller => "game_picks", :method => "index", :week => "12" }%>|
    <%= link_to "13", {:controller => "game_picks", :method => "index", :week => "13" }%>|
    <%= link_to "14", {:controller => "game_picks", :method => "index", :week => "14" }%>|
    <%= link_to "15", {:controller => "game_picks", :method => "index", :week => "15" }%>|
    <%= link_to "16", {:controller => "game_picks", :method => "index", :week => "16" }%>|
    <%= link_to "17", {:controller => "game_picks", :method => "index", :week => "17" }%>
  </p>
</div>

<div id="margin">
<table class="table table-bordered">
  <thead class="thead-light">
    <tr>
      <th scope="col">HomeTeam</th>
      <th scope="col">AwayTeam</th>
      <th scope="col">GameDateTime</th>
      <th scope="col">Week</th>
      <th scope="col">Pickedteam</th>
      <th scope="col">Spread</th>
<!--       <th scope="col" colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @game_infos.each do |game_info| %>
      <tr>
        <td><%= game_info["schedule"]["homeTeam"]["abbreviation"] %></td>
        <td><%= game_info["schedule"]["awayTeam"]["abbreviation"] %></td>
        <td><%= DateTime.parse(game_info["schedule"]["startTime"]).new_offset("-04:00").strftime("%m/%d/%y %l:%M %p") %></td>
        <td><%= game_info["schedule"]["week"] %></td>
        <td><%= form_with do |form| %><%= form.select game_info["schedule"]["pickedTeam"], options_for_select([game_info["schedule"]["homeTeam"]["abbreviation"], game_info["schedule"]["awayTeam"]["abbreviation"]], selected: game_info["schedule"]["pickedTeam"]), {}, {class: "form-control pick"} %><% end %></td>
        <td><%= form_with do |form| %><%= form.number_field game_info["schedule"]["spread"], value: game_info["schedule"]["spread"], :class => 'form-control spread' %><% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<button type="button" class="btn btn-lg btn-primary color-button" id="saveButton">Save</button>

app/views/game_picks/new.html.erb
<h1>New Game Pick</h1>

<%= render 'form', game_pick: @game_pick %>

<%= link_to 'Back', game_picks_path %>

app/views/game_picks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team1:</strong>
  <%= @game_pick.team1 %>
</p>

<p>
  <strong>Team2:</strong>
  <%= @game_pick.team2 %>
</p>

<p>
  <strong>Week:</strong>
  <%= @game_pick.week %>
</p>

<p>
  <strong>Pickedteam:</strong>
  <%= @game_pick.pickedteam %>
</p>

<p>
  <strong>Spread:</strong>
  <%= @game_pick.spread %>
</p>

<%= link_to 'Edit', edit_game_pick_path(@game_pick) %> |
<%= link_to 'Back', game_picks_path %>